// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTnh5mXfr6dfavgzXyVs4S2m38ISiSB5c',
    appId: '1:435607360361:web:68893c65f280627b4723f8',
    messagingSenderId: '435607360361',
    projectId: 'pencil-6bbbc',
    authDomain: 'pencil-6bbbc.firebaseapp.com',
    storageBucket: 'pencil-6bbbc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_VSWiJhH5knGr0IyJ08e9iXMykO7SK4Y',
    appId: '1:435607360361:android:86793242346b275f4723f8',
    messagingSenderId: '435607360361',
    projectId: 'pencil-6bbbc',
    storageBucket: 'pencil-6bbbc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdhOvmuWigb-J0pa6TRK3NWnToD5OJTTk',
    appId: '1:435607360361:ios:d28f55b5489c69614723f8',
    messagingSenderId: '435607360361',
    projectId: 'pencil-6bbbc',
    storageBucket: 'pencil-6bbbc.firebasestorage.app',
    iosClientId: '435607360361-pcaa1erf7g743lh8p4en84dhguc7rdep.apps.googleusercontent.com',
    iosBundleId: 'com.example.pencil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdhOvmuWigb-J0pa6TRK3NWnToD5OJTTk',
    appId: '1:435607360361:ios:d28f55b5489c69614723f8',
    messagingSenderId: '435607360361',
    projectId: 'pencil-6bbbc',
    storageBucket: 'pencil-6bbbc.firebasestorage.app',
    iosClientId: '435607360361-pcaa1erf7g743lh8p4en84dhguc7rdep.apps.googleusercontent.com',
    iosBundleId: 'com.example.pencil',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTnh5mXfr6dfavgzXyVs4S2m38ISiSB5c',
    appId: '1:435607360361:web:f0faa77abf921b374723f8',
    messagingSenderId: '435607360361',
    projectId: 'pencil-6bbbc',
    authDomain: 'pencil-6bbbc.firebaseapp.com',
    storageBucket: 'pencil-6bbbc.firebasestorage.app',
  );

}